export const menuItems = [
    {
      id: 1,
      category: "menu",
      image: "https://via.placeholder.com/300",
      title: "Couscous Royal",
      description: "Un plat traditionnel avec de la semoule cuite à la vapeur, des légumes et un mélange de viandes.",
      price: 18,
      buttonText: "Commander",
    },
    {
      id: 2,
      category: "menu",
      image: "https://via.placeholder.com/300",
      title: "Tagine d'Agneau",
      description: "Agneau mijoté dans une sauce savoureuse avec des fruits secs et des épices.",
      price: 20,
      buttonText: "Commander",
    },
    {
      id: 3,
      category: "menu",
      image: "https://via.placeholder.com/300",
      title: "Biryani",
      description: "Un plat de riz parfumé avec du poulet mariné, des épices et du safran.",
      price: 16,
      buttonText: "Commander",
    },
    {
      id: 4,
      category: "menu",
      image: "https://via.placeholder.com/300",
      title: "Poulet Grillé",
      description: "Un poulet grillé succulent servi avec des légumes vapeur.",
      price: 14,
      buttonText: "Commander",
    },
    {
      id: 5,
      category: "menu",
      image: "https://via.placeholder.com/300",
      title: "Paella aux Légumes",
      description: "Un plat espagnol à base de riz avec une variété de légumes frais.",
      price: 15,
      buttonText: "Commander",
    },
    {
      id: 6,
      category: "pizza",
      image: "https://via.placeholder.com/300",
      title: "Pizza Margherita",
      description: "Pizza italienne classique avec sauce tomate, mozzarella et basilic frais.",
      price: 10,
      buttonText: "Commander",
    },
    {
      id: 7,
      category: "pizza",
      image: "https://via.placeholder.com/300",
      title: "Pizza Pepperoni",
      description: "Pizza garnie de pepperoni et de fromage mozzarella fondant.",
      price: 12,
      buttonText: "Commander",
    },
    {
      id: 8,
      category: "pizza",
      image: "https://via.placeholder.com/300",
      title: "Pizza Végétarienne",
      description: "Un mélange délicieux de légumes de saison, mozzarella et sauce tomate.",
      price: 11,
      buttonText: "Commander",
    },
    {
      id: 9,
      category: "pizza",
      image: "https://via.placeholder.com/300",
      title: "Pizza Poulet BBQ",
      description: "Poulet grillé avec sauce barbecue, oignons rouges et mozzarella.",
      price: 13,
      buttonText: "Commander",
    },
    {
      id: 10,
      category: "pizza",
      image: "https://via.placeholder.com/300",
      title: "Pizza Hawaïenne",
      description: "Pizza sucrée et salée avec ananas, jambon et mozzarella.",
      price: 12,
      buttonText: "Commander",
    },
    {
      id: 11,
      category: "burger",
      image: "https://via.placeholder.com/300",
      title: "Cheeseburger",
      description: "Un steak juteux garni de fromage fondu, laitue et tomate.",
      price: 12,
      buttonText: "Commander",
    },
    {
      id: 12,
      category: "burger",
      image: "https://via.placeholder.com/300",
      title: "Burger Bacon",
      description: "Un burger avec bacon croustillant, fromage cheddar et laitue fraîche.",
      price: 14,
      buttonText: "Commander",
    },
    {
      id: 13,
      category: "burger",
      image: "https://via.placeholder.com/300",
      title: "Burger Végétarien",
      description: "Un steak végétarien délicieux avec laitue, tomate et avocat.",
      price: 11,
      buttonText: "Commander",
    },
    {
      id: 14,
      category: "burger",
      image: "https://via.placeholder.com/300",
      title: "Double Cheeseburger",
      description: "Deux steaks, deux couches de fromage, laitue et cornichons.",
      price: 16,
      buttonText: "Commander",
    },
    {
      id: 15,
      category: "burger",
      image: "https://via.placeholder.com/300",
      title: "Burger BBQ",
      description: "Un burger avec sauce BBQ, rondelles d'oignons croustillantes et fromage cheddar.",
      price: 15,
      buttonText: "Commander",
    },
    {
      id: 16,
      category: "limonade",
      image: "https://via.placeholder.com/300",
      title: "Limonade Fraîche",
      description: "Boisson rafraîchissante faite avec des citrons pressés frais.",
      price: 5,
      buttonText: "Commander",
    },
    {
      id: 17,
      category: "limonade",
      image: "https://via.placeholder.com/300",
      title: "Limonade à la Fraise",
      description: "Une limonade classique avec une touche de fraises fraîches.",
      price: 6,
      buttonText: "Commander",
    },
    {
      id: 18,
      category: "limonade",
      image: "https://via.placeholder.com/300",
      title: "Limonade à la Menthe",
      description: "Un mélange rafraîchissant de menthe et de citrons pressés.",
      price: 6,
      buttonText: "Commander",
    },
    {
      id: 19,
      category: "limonade",
      image: "https://via.placeholder.com/300",
      title: "Limonade à la Pêche",
      description: "Une limonade fruitée à base de pêches fraîches.",
      price: 6,
      buttonText: "Commander",
    },
    {
      id: 20,
      category: "limonade",
      image: "https://via.placeholder.com/300",
      title: "Limonade au Concombre",
      description: "Une limonade rafraîchissante avec une touche de concombre.",
      price: 6,
      buttonText: "Commander",
    },
    {
      id: 21,
      category: "glace",
      image: "https://via.placeholder.com/300",
      title: "Glace au Chocolat",
      description: "Une glace riche et crémeuse au chocolat pour les gourmands.",
      price: 6,
      buttonText: "Commander",
    },
    {
      id: 22,
      category: "glace",
      image: "https://via.placeholder.com/300",
      title: "Glace à la Vanille",
      description: "Une glace classique à la vanille faite avec de véritables gousses de vanille.",
      price: 5,
      buttonText: "Commander",
    },
    {
      id: 23,
      category: "glace",
      image: "https://via.placeholder.com/300",
      title: "Glace à la Fraise",
      description: "Une glace douce et crémeuse à la fraise avec de vrais fruits.",
      price: 6,
      buttonText: "Commander",
    },
    {
      id: 24,
      category: "glace",
      image: "https://via.placeholder.com/300",
      title: "Glace Menthe-Choco",
      description: "Une glace rafraîchissante à la menthe avec des pépites de chocolat croquantes.",
      price: 7,
      buttonText: "Commander",
    },
    {
      id: 25,
      category: "glace",
      image: "https://via.placeholder.com/300",
      title: "Glace Cookies & Cream",
      description: "Une glace crémeuse à la vanille avec des morceaux de biscuits croustillants.",
      price: 7,
      buttonText: "Commander",
    },
  ];
  