export const menuItems = [
    {
      id: 1,
      category: "plat traditionel",
      image: "https://via.placeholder.com/300",
      title: "Couscous Royal",
      description: "A traditional dish with steamed semolina, vegetables, and a mix of meats.",
      price: 18,
      buttonText: "Order",
    },
    {
      id: 2,
      category: "pizza",
      image: "https://via.placeholder.com/300",
      title: "Margherita Pizza",
      description: "Classic Italian pizza with tomato sauce, mozzarella, and fresh basil.",
      price: 10,
      buttonText: "Order",
    },
    {
      id: 3,
      category: "burger",
      image: "https://via.placeholder.com/300",
      title: "Cheeseburger",
      description: "A juicy beef patty topped with melted cheese, lettuce, and tomato.",
      price: 12,
      buttonText: "Order",
    },
    {
      id: 4,
      category: "limonade",
      image: "https://via.placeholder.com/300",
      title: "Fresh Lemonade",
      description: "Refreshing drink made with freshly squeezed lemons.",
      price: 5,
      buttonText: "Order",
    },
    {
      id: 5,
      category: "glace",
      image: "https://via.placeholder.com/300",
      title: "Chocolate Ice Cream",
      description: "Rich and creamy chocolate ice cream to satisfy your sweet tooth.",
      price: 6,
      buttonText: "Order",
    },
  ];
  